export const userinyerface = {
    startButton: '.start__button',
    startLink: '.start__link',
    game: '.game',
    helpButton: 'a[class*="help-button"]',
    helpResponse: '.help-form__response',
    timer: '.timer',
    emailField: 'input[placeholder="Your email"]',
    domainField: 'input[placeholder="Domain"]',
    passwordField: 'input[placeholder="Choose Password"]',
    conditionsCheckbox: '.checkbox__box',
    nextLink: 'Next',
    pageIndicator: '.page-indicator'
};

export const euronews = {
    agreeCookiesButton: '#didomi-notice-agree-button',
    topTags: '[class*="tag-list"]',
    views: '.b-topstories-home',
    viewsTitles: '.b-topstories-home__aside__article h2 a',
    viewTitle: '.jsArticleFirst.swiper-slide-active h1',
    programsButton: '.c-programs-icon',
    programsTitles: '.c-programs-menu__categories .title',
    topicLinks: '.list-item__link',
    topic: 'Europe Decoded',
    labels: '.program-name',
    programsDropdown: '.c-programs-icon',
    programsLink: 'All Programmes',
    programs: '.c-program-card',
    newslettersLink: 'Newsletters',
    newsletters: '.p-8',
    newsletterText: 'h2',
    frequencyText: '.mt-2',
    descriptionText: '.mt-4',
    createAccountPopup: '.cta-newsletter-esturgeon',
    chosenButton: '.btn-tertiary-plain',
    emailFieldPopup: '[type="email"]',
    continueButton: '[value="Continue"]',
    emailField: 'input[id*="loginID"]',
    passwordField: 'input[id*="password"]',
    createAccountButton: 'input[value="Create my account"]',
    confirmationMessage: 'Thank you, check your emails'
};
